external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]

#==================
#=== Substitutions
#==================
substitutions:
  device_name: new-kitchen-sensor-hub
  friendly_name: Multi-Sensore Cucina

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: ${device_name}

i2c:
  - id: bus_a
    sda: 18
    scl: 19
    scan: true
    
spi:
  mosi_pin: GPIO13
  clk_pin: GPIO14

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: false
  password: !secret ota_password    

time:
  - platform: homeassistant
    id: esptime

  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome

esp32_ble_tracker:
  scan_parameters:
    active: false

sensor: 
  - platform: bme280
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: ${friendly_name} Temperatura
      id: bme280_temperature
      filters:
        - lambda: return x;
    pressure:
      name: ${friendly_name} Pressione atmosferica
      id: bme280_pressure
    humidity:
      name: ${friendly_name} Umidità relativa
      id: bme280_humidity
      filters:
        - lambda: return x + 7;
    update_interval: 30s  

  - platform: template
    name: ${friendly_name} Umidità assoluta
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 30s
    icon: "mdi:water"
    unit_of_measurement: "g/m³"

  - platform: template
    name: ${friendly_name} Punto di rugiada
    lambda: |-
      return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
      (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
      ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
    unit_of_measurement: °C
    icon: "mdi:thermometer-alert"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora_mac_address
    temperature:
      name: "Bonsai Ficus temperatura"
    moisture:
      name: "Bonsai Ficus umidità"
    illuminance:
      name: "Bonsai Ficus luminanza"
    conductivity:
      name: "Bonsai Ficus fertilità terreno"
    battery_level:
      name: "Bonsai Ficus livello batteria"

button:
  - platform: restart
    name: Restart ${device_name}

# Some fonts & images to display
font:
  - file: "Fonts/high_sans_serif_7.ttf"
    id: font40_serif
    size: 40   


# OLED SSD1306 configurations
display:
  - platform: gc9a01
    reset_pin: GPIO26
    cs_pin: GPIO15
    dc_pin: GPIO33
    rotation: 90
    lambda: |-
      it.strftime(44, -8, id(font40_serif), "%d %b %Y", id(esptime).now());
