#==================
#=== Substitutions
#==================
substitutions:
  device_name: new-kitchen-sensor-hub
  friendly_name: Multi-Sensore Cucina

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: ${device_name}
  id: mqtt_client
  birth_message:
    topic: "${device_name}/status"
    payload: "online"
  will_message:
    topic: "${device_name}/status"
    payload: "offline"

i2c:
  - id: bus_a
    sda: 18
    scl: 19
    scan: true

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: false
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    active: false

binary_sensor:
  - platform: gpio
    pin: 
      number: 33
      mode: INPUT_PULLUP
    name: ${device_name} Sensore movimento
    id: sensore_movimento
    device_class: motion 
    icon: "mdi:motion-sensor"   

sensor: 
  - platform: adc
    pin: GPIO34
    name: "Sensore Gas"
    id: gas_sensor
    update_interval: 10s
    filters:
      - calibrate_linear:
          - 0.1 -> 0.0
          - 1.0 -> 1.0

  - platform: template
    name: "Gas PPM"
    id: gas_ppm_sensor
    update_interval: 10s
    accuracy_decimals: 2
    lambda: |-
      float resistance = 10.0 * (4096.0 / id(gas_sensor).state - 1.0);
      ESP_LOGD("gas_ppm_sensor", "The value of resistance is %.1f", resistance);
      float ppm = pow(10, (log10(resistance) - log10(1036.0)) / -0.616);
      ESP_LOGD("gas_ppm_sensor", "The value of ppm is %.1f", ppm);
      return ppm;

  - platform: bme280
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: ${friendly_name} Temperatura
      id: bme280_temperature
      filters:
        - lambda: return x;
    pressure:
      name: ${friendly_name} Pressione atmosferica
      id: bme280_pressure
    humidity:
      name: ${friendly_name} Umidità relativa
      id: bme280_humidity
      filters:
        - lambda: return x + 7;
    update_interval: 10s  

  - platform: template
    name: ${friendly_name} Umidità assoluta
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 10s
    icon: "mdi:water"
    unit_of_measurement: "g/m³"

  - platform: template
    name: ${friendly_name} Punto di rugiada
    lambda: |-
      return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
      (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
      ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
    unit_of_measurement: °C
    update_interval: 10s
    icon: "mdi:thermometer-alert"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora_mac_address
    temperature:
      name: "Bonsai Ficus temperatura"
    moisture:
      name: "Bonsai Ficus umidità"
    illuminance:
      name: "Bonsai Ficus luminanza"
    conductivity:
      name: "Bonsai Ficus fertilità terreno"
    battery_level:
      name: "Bonsai Ficus livello batteria"

uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  debug:
    direction: TX
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

# "<NO MSG,0,59.0,26.3,987.97>"
interval:
  - interval: 5s
    then:
    - uart.write: !lambda  
                        char buf[42];
                        sprintf(buf, "<ALARM MSG,0,%.1f,%.1f,%.2f>\r\n", id(bme280_humidity).state, id(bme280_temperature).state, id(bme280_pressure).state);
                        std::string s = buf;
                        return std::vector<unsigned char>( s.begin(), s.end() );

button:
  - platform: restart
    name: Restart ${device_name}