#==================
#=== Substitutions
#==================
substitutions:
  device_name: new-kitchen-sensor-hub
  friendly_name: Multi-Sensore Cucina

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: ${device_name}

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: false
  password: !secret ota_password    

time:
  - platform: homeassistant
    id: esptime

  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome

esp32_ble_tracker:
  scan_parameters:
    active: false

sensor: 
  - platform: bme280
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: ${friendly_name} Temperatura
      id: bme280_temperature
      filters:
        - lambda: return x;
    pressure:
      name: ${friendly_name} Pressione atmosferica
      id: bme280_pressure
    humidity:
      name: ${friendly_name} Umidità relativa
      id: bme280_humidity
      filters:
        - lambda: return x + 7;
    update_interval: 30s  

  - platform: template
    name: ${friendly_name} Umidità assoluta
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 30s
    icon: "mdi:water"
    unit_of_measurement: "g/m³"

  - platform: template
    name: ${friendly_name} Punto di rugiada
    lambda: |-
      return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
      (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
      ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
    unit_of_measurement: °C
    icon: "mdi:thermometer-alert"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora_mac_address
    temperature:
      name: "Bonsai Ficus temperatura"
    moisture:
      name: "Bonsai Ficus umidità"
    illuminance:
      name: "Bonsai Ficus luminanza"
    conductivity:
      name: "Bonsai Ficus fertilità terreno"
    battery_level:
      name: "Bonsai Ficus livello batteria"

uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  debug:
    direction: TX
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

# "<TX_MSG,1671289668,66.9,15.4,991.45>"
interval:
  - interval: 5s
    then:
    - uart.write: !lambda  
                        char buf[42];
                        char str[17];
                        long currTime = id(sntp_time).now().timestamp;
                        sprintf(buf, "<TX_MSG,0,%lu,%.1f,%.1f,%.2f>\r\n", currTime, id(bme280_humidity).state, id(bme280_temperature).state, id(bme280_pressure).state);
                        std::string s = buf;
                        return std::vector<unsigned char>( s.begin(), s.end() );

button:
  - platform: restart
    name: Restart ${device_name}