external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]

#==================
#=== Substitutions
#==================
substitutions:
  device_name: new-kitchen-sensor-hub
  friendly_name: Multi-Sensore Cucina

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  mosi_pin: GPIO13
  clk_pin: GPIO14

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: false
  password: !secret ota_password    

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome

# Some fonts & images to display
font:
  - file: "Fonts/high_sans_serif_7.ttf"
    id: font40_serif
    size: 40   


# OLED SSD1306 configurations
display:
  - platform: gc9a01
    reset_pin: GPIO26
    cs_pin: GPIO25
    dc_pin: GPIO33
    rotation: 90
    lambda: |-
      it.strftime(44, -8, id(font40_serif), "%d %b %Y", id(sntp_time).now());

button:
  - platform: restart
    name: Restart ${device_name}