external_components:
  - source: github://bigmoby/esphome@gc9a01
    components: ["gc9a01"]

#==================
#=== Substitutions
#==================
substitutions:
  device_name: kitchen-sensor-hub-receiver
  friendly_name: Multi-Sensore Receiver Cucina
  update_time: 900s

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome  

spi:
  mosi_pin: GPIO13 # SDA
  clk_pin: GPIO14  # SCL

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:
    direction: RX
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);  

display:
- platform: gc9a01
  reset_pin: GPIO18
  cs_pin: GPIO16
  dc_pin: GPIO33
  rotation: 180
  lambda: |-  
      it.strftime(80, 10, id(font40_serif), "%d %b %Y", id(sntp_time).now());
      // Print time in HH:MM format
      it.strftime(90, 63, id(font68_serif),  "%H:%M", id(sntp_time).now());

font:
  - file: "Roboto-Light.ttf"
    id: font8
    size: 8

  - file: "arial.ttf"
    id: font14
    size: 20

  - file: "high_sans_serif_7.ttf"
    id: font40_serif
    size: 40    

  - file: "high_sans_serif_7.ttf"
    id: font68_serif
    size: 68    

  # https://pictogrammers.com/library/mdi/ 
  - file: 'materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    glyphs:
      - "\U000F050F" # mdi-thermometer
      - "\U000F058E" # mdi-water-percent
      - "\U000F029A" # mdi-gauge   