external_components:
  - source: github://bigmoby/esphome@gc9a01
    components: ["gc9a01"]

#==================
#=== Substitutions
#==================
substitutions:
  device_name: kitchen-sensor-hub-receiver
  friendly_name: Multi-Sensore Receiver Cucina

esp8266:
  board: nodemcuv2
  framework:
    version: recommended
  restore_from_flash: true

esphome:
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: false
  password: !secret ota_password  

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome  

spi:
  mosi_pin: GPIO13 # SDA
  clk_pin: GPIO14  # SCL



display:
  - platform: gc9a01
    reset_pin: GPIO05
    cs_pin: GPIO10
    dc_pin: GPIO15
    rotation: 0
    lambda: |-  
      ESP_LOGD("gc9a01", "Write to display start");
      it.line(0, 0, 50, 50);
      ESP_LOGD("gc9a01", "Write to display end");

font:
  - file: "Roboto-Light.ttf"
    id: font8
    size: 8

  - file: "arial.ttf"
    id: font14
    size: 20

  - file: "high_sans_serif_7.ttf"
    id: font40_serif
    size: 40    

  - file: "high_sans_serif_7.ttf"
    id: font68_serif
    size: 68    

  # https://pictogrammers.com/library/mdi/ 
  - file: 'materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    glyphs:
      - "\U000F050F" # mdi-thermometer
      - "\U000F058E" # mdi-water-percent
      - "\U000F029A" # mdi-gauge   s