external_components:
  - source: github://bigmoby/esphome@gc9a01
    components: ["gc9a01"]

#==================
#=== Substitutions
#==================
substitutions:
  device_name: kitchen-sensor-hub-receiver
  friendly_name: Multi-Sensore Receiver Cucina
  update_time: 5s

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  includes:
    - uart_read_line_sensor.h
  name: ${device_name}
  project:
    name: "Bigmoby.${device_name}"
    version: "2.1.0"

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart

uart:
  - id: uart_bus
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes); 

spi:
  - id: bus_a
    mosi_pin: GPIO13
    clk_pin: GPIO14

display:
  - platform: gc9a01
    spi_id: bus_a
    reset_pin: GPIO26
    cs_pin: GPIO15
    dc_pin: GPIO33
    rotation: 0
    update_interval: ${update_time}
    lambda: |-  
      //it.strftime(80, 10, id(font40_serif), "%d %b %Y", id(sntp_time).now());
      it.print(40, 40, id(font40_serif), "Hello World!");
      // Print time in HH:MM format
      //it.strftime(90, 63, id(font68_serif),  "%H:%M", id(sntp_time).now());
      // ESP_LOGD("gc9a01", "Value of my sensor: %s", id(uart_readline).state);
      // it.print(40, 80, id(font14), id(uart_readline).state);

sensor:
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor->header_message_sensor,my_custom_sensor->alarm_status_code_sensor,my_custom_sensor->current_time_sensor,my_custom_sensor->humidity_sensor,my_custom_sensor->temperature_sensor, my_custom_sensor->pressure_sensor};

    sensors:
      - name: "header_message_sensor"
        unit_of_measurement: 째C
        accuracy_decimals: 1
      - name: "alarm_status_code_sensor"
        unit_of_measurement: 째C
        accuracy_decimals: 1
      - name: "current_time_sensor"
        unit_of_measurement: 째C
        accuracy_decimals: 1
      - name: "humidity_sensor"
        unit_of_measurement: hPa
        accuracy_decimals: 2
      - name: "temperature_sensor"
        unit_of_measurement: 째C
        accuracy_decimals: 1
      - name: "pressure_sensor"
        unit_of_measurement: hPa
        accuracy_decimals: 1

font:
  - file: "Roboto-Light.ttf"
    id: font8
    size: 8

  - file: "arial.ttf"
    id: font14
    size: 20

  - file: "high_sans_serif_7.ttf"
    id: font40_serif
    size: 40    

  - file: "high_sans_serif_7.ttf"
    id: font68_serif
    size: 68    

  # https://pictogrammers.com/library/mdi/ 
  - file: 'materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    glyphs:
      - "\U000F050F" # mdi-thermometer
      - "\U000F058E" # mdi-water-percent
      - "\U000F029A" # mdi-gauge   

button:
  - platform: restart
    name: Restart ${device_name}